version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: irenes-circus-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=irenes-circus
    command: ["mongod", "--logpath=/dev/null"]

  backend:
    build:
      context: ./irenes-circus-backend
      dockerfile: Dockerfile
    container_name: irenes-circus-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-5000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/irenes-circus}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID:-}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET:-}
    depends_on:
      - mongodb
    expose:
      - "5000"

  web:
    build:
      context: ./irenes-circus-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-/api}
    container_name: irenes-circus-web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongodb_data: 