services:
  # MongoDB Database
  - type: pserv
    name: irenes-circus-mongodb
    env: docker
    dockerfilePath: ./mongo-dockerfile
    plan: free
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: admin
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: admin123
      - key: MONGO_INITDB_DATABASE
        value: irenes-circus

  # Backend API Service
  - type: web
    name: irenes-circus-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd irenes-circus-backend && pnpm install && pnpm build
    startCommand: cd irenes-circus-backend && pnpm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb://admin:admin123@irenes-circus-mongodb:27017/irenes-circus
      - key: JWT_SECRET
        value: a8f5f167f44f4964e6c998dee827110c89b7e8f8d12345678901234567890123
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: LOG_LEVEL
        value: info
      - key: FRONTEND_URL
        fromService:
          type: web
          name: irenes-circus-frontend
          property: host

  # Frontend Static Site
  - type: web
    name: irenes-circus-frontend
    env: static
    plan: starter
    buildCommand: cd irenes-circus-frontend && pnpm install && pnpm build
    staticPublishPath: ./irenes-circus-frontend/dist
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
      - irenes-circus-frontend/**
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: irenes-circus-backend
          property: host
      - key: NODE_ENV
        value: production

# Note: Using Docker MongoDB instead of managed database for hobby plan
# databases:
#   - name: irenes-circus-db
#     databaseName: irenes-circus
#     user: irenes-circus-user
#     plan: free

# Note: Database seeding will be handled automatically by the backend on first startup
