services:
  # MongoDB Database
  - type: pserv
    name: irenes-circus-mongodb
    env: docker
    dockerfilePath: ./mongo-dockerfile
    plan: free
    disk:
      name: mongodb-data
      mountPath: /data/db
      sizeGB: 10
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: admin
      - key: MONGO_INITDB_ROOT_PASSWORD
        sync: false  # Set this manually in Render dashboard
      - key: MONGO_INITDB_DATABASE
        value: irenes-circus

  # Backend API Service
  - type: web
    name: irenes-circus-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd irenes-circus-backend && pnpm install && pnpm build
    startCommand: cd irenes-circus-backend && pnpm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb://admin:${MONGO_PASSWORD}@irenes-circus-mongodb:27017/irenes-circus
      - key: JWT_SECRET
        sync: false  # This will be set manually in Render dashboard
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: LOG_LEVEL
        value: info
      - key: FRONTEND_URL
        fromService:
          type: web
          name: irenes-circus-frontend
          property: host
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/*

  # Frontend Static Site
  - type: web
    name: irenes-circus-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd irenes-circus-frontend && pnpm install && pnpm build
    staticPublishPath: ./irenes-circus-frontend/dist
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
      - irenes-circus-frontend/**
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: irenes-circus-backend
          property: host
      - key: NODE_ENV
        value: production

# Note: Using Docker MongoDB instead of managed database for hobby plan
# databases:f
#   - name: irenes-circus-db
#     databaseName: irenes-circus
#     user: irenes-circus-user
#     plan: free

# Database seeding job
jobs:
  - type: job
    name: seed-database
    env: node
    buildCommand: cd irenes-circus-backend && pnpm install && pnpm build
    startCommand: cd irenes-circus-backend && pnpm seed:production
    plan: free
    schedule: "@once"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromService:
          type: pserv
          name: irenes-circus-mongodb
          property: connectionString
